### ISSUE TITLE
AppCatalyst TP2 won't boot Debian "Jessie" Vagrant boxes

### ISSUE THREAD

**Issue by scottslowe** [vmware/vagrant-vmware-appcatalyst#15]
I'm seeing an issue similar to #5, but the fix described in that issue (set the `guestos` value to `other3xlinux-64`) does not fix the problem. This issue is observed trying to boot a Debian "Jessie" Vagrant box built using Packer. I've tried this with both Debian 8.1 as well as Debian 8.0, and the same error occurs in both cases.

The Packer templates used to build the Vagrant boxes are here:

Debian 8.0: https://github.com/lowescott/packer-templates/blob/master/templates/jessie80.json
Debian 8.1: https://github.com/lowescott/packer-templates/blob/master/templates/jessie81.json

The `Vagrantfile` I'm using is available here: https://gist.github.com/lowescott/b63e3c14a34bf4b52a9d

No vmware.log file is being created when I attempt to run `vagrant up`.

The `.vagrant` directory and all subdirectories are currently empty (I've just run a `vagrant destroy -f`). If it would be useful, I can supply the output of `ls -lR .vagrant` so that you can see the files and directories being created.

This error is occurring w/ AppCatalyst TP2, on OS X 10.9.5, with Fusion 7.1.2 also installed (but not running at any time when these errors occur).

**Comment by frapposelli** [comment]
Please rerun a `vagrant up` with `VAGRANT_LOG=DEBUG` and once it errors out collect a `ls -lR .vagrant`.

The canceled power on (and the consequent vagrant error) should show up when trying to run unauthorized virtual hardware: 3D SVGA, Virtual Hardware < 11, Windows or Mac OS guest type. So this shouldn't be your case here.

Also, make sure (when you have Fusion and AppCatalyst installed on the same machine) that when no VMs are running a `kextstat | grep vm` reports no loaded modules.

**Comment by scottslowe** [comment]
@frapposelli, I can confirm that when no VMs are running, the `kextstat | grep vm` command returns no loaded modules.

Oddly enough, after working on this for over 2 hours last night, the Vagrant box I just tried (Debian 8.1 64-bit) booted successfully and without any errors. I'm going to try some additional tests to see if I can recreate the error again. Stay tuned.

**Comment by scottslowe** [comment]
I can't seem to replicate the problem, so I'll go ahead and close this issue. Sorry for the false alarm!
