### ISSUE TITLE
Feature: plugin should deal with locally named boxes.

### ISSUE THREAD

**Issue by Snergster** [vmware/vagrant-vmware-appcatalyst#17]
if i add a box with 
vagrant box add -name foo ./build/foo.box
I should just like with the fusion plugin be able to refer to it in the VagrantFile with just
config.vm.box = 'foo'
at present I have to supply the url its really kinda a nit I know but at least for testing when I'm constantly flipping back and forth between fusion and appcatalyst its just one of those annoying things.
thanks

**Comment by frapposelli** [comment]
I'm not sue what you mean, you can definitely add a box and reference it as you say, can you give me a `Vagrantfile` example that doesn't work as expected?

**Comment by Snergster** [comment]
I can't repro this right now happily so will close until i can
